export default [
    {
        codigo: '2000101',
        descripcion: 'Molida cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 106,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 260,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },    
    {
        codigo: '2000100',
        descripcion: 'Nalga cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 106,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 470,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000206',
        descripcion: 'Cuadrada cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 106,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 425,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000211',
        descripcion: 'Lomo cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 106,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 455,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }        
]

