export default [
    {
        codigo: '2000100',
        descripcion: 'Nalga cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 470,
        precio: 470,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000101',
        descripcion: 'Molida cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 260,
        precio: 260,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000202',
        descripcion: 'Costilla cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 455,
        precio: 455,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000203',
        descripcion: 'Matambre cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 545,
        precio: 545,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000204',
        descripcion: 'Costeleta cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 450,
        precio: 450,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },  
    {
        codigo: '2000205',
        descripcion: 'Bondiola',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 540,
        precio: 540,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000206',
        descripcion: 'Cuadrada cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 425,
        precio: 425,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000207',
        descripcion: 'Cuadril cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 425,
        precio: 425,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000208',
        descripcion: 'Nalga cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 425,
        precio: 425,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000209',
        descripcion: 'Bola de lomo cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 425,
        precio: 425,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000210',
        descripcion: 'Colita de cuadril',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 425,
        precio: 425,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },   
    {
        codigo: '2000211',
        descripcion: 'Lomo cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 455,
        precio: 455,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000212',
        descripcion: 'Corte obispo cerdo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 465,
        precio: 465,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }          
]

