export default [
    {
        codigo: '1',
        descripcion: 'Media completa',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 106,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },  
    {
        codigo: '2',
        descripcion: 'Aguja',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 11.67,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '3',
        descripcion: 'Asado carnicero',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 2.245,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '4',
        descripcion: 'Bola de lomo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.945,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '5',
        descripcion: 'Colita de cuadril',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0.895,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '6',
        descripcion: 'Costeleta',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 9.51,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '7',
        descripcion: 'Costilla',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 6.715,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '8',
        descripcion: 'Cuadrada',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.9625,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '9',
        descripcion: 'Cuadril',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 2.6,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '10',
        descripcion: 'Falda',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.09,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    }, 
    {
        codigo: '11',
        descripcion: 'Lomo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.59,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '12',
        descripcion: 'Matambre',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.61,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '13',
        descripcion: 'Milanesas',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.9625,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '14',
        descripcion: 'Molida comun',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 7.64,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '15',
        descripcion: 'Molida especial',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.22,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '16',
        descripcion: 'Nalga',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 4.06,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '17',
        descripcion: 'Osobuco',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.625,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '18',
        descripcion: 'Paleta con hueso',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 6.93,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '19',
        descripcion: 'Peceto',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.59,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '20',
        descripcion: 'Tapa de asado',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 2.03,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    },
    {
        codigo: '21',
        descripcion: 'Vacio',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.335,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        activo: true
    }                              

]

