export default [
    {
        codigo: '1',
        descripcion: 'Media completa',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 106,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },  
    {
        codigo: '2000026',
        descripcion: 'Aguja',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 11.67,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 718,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000003',
        descripcion: 'Asado carnicero',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 2.245,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 861,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000012',
        descripcion: 'Bola de lomo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.945,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 818,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000014',
        descripcion: 'Colita de cuadril',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0.895,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 876,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000022',
        descripcion: 'Costeleta',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 9.51,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 770,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000021',
        descripcion: 'Costilla',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 6.715,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 679,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000016',
        descripcion: 'Cuadrada',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.9625,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 818,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000017',
        descripcion: 'Cuadril',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 2.6,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 889,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000006',
        descripcion: 'Falda',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.09,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 719,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000018',
        descripcion: 'Lomo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.59,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 921,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000001',
        descripcion: 'Matambre',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.61,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 875,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000011',
        descripcion: 'Milanesa de carne',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.9625,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 575,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000008',
        descripcion: 'Molida comun',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 7.64,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 469,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000007',
        descripcion: 'Molida especial',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.22,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 709,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000013',
        descripcion: 'Nalga',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 4.06,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 885,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '17',
        descripcion: 'Osobuco',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.625,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 0,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000020',
        descripcion: 'Paleta',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 6.93,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 712,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000015',
        descripcion: 'Peceto',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 1.59,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 932,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000002',
        descripcion: 'Tapa de asado',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 2.03,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 855,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000004',
        descripcion: 'Vacio',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 3.335,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 0,
        precio: 887,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }                              

]

