export default [
    {
        codigo: '2000302',
        descripcion: 'Pollo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 219,
        precio: 219,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },    
    {
        codigo: '2000303',
        descripcion: 'Cuarto trasero',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 305,
        precio: 305,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },   
    {
        codigo: '2000304',
        descripcion: 'Pechuga',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 555,
        precio: 555,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    }, 
    {
        codigo: '2000305',
        descripcion: 'Puchero pollo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 69,
        precio: 69,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000307',
        descripcion: 'Alitas',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 199,
        precio: 199,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000309',
        descripcion: 'Pechuga con hueso',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 399,
        precio: 399,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
    {
        codigo: '2000311',
        descripcion: 'Pata muslo',
        unidad_medida: '',
        cantidad: 0,
        cantidad_estandar: 0,
        stock_minimo: false,
        cantidad_minima: 0,
        porcentaje_ganancia : 40,
        precio_costo: 370,
        precio: 370,
        promocion: false,
        precio_promocion: 0,
        tipo: 'Balanza',
        carne: true,
        activo: true
    },
]

